'use client';

import { useMemo, useState } from 'react';

declare global { interface Window { gtag?: (...args: unknown[]) => void } }
const STATUSES = ['New', 'Contacted', 'Qualified', 'Estimate Scheduled', 'Estimate Sent', 'Won', 'Lost'];
type Lead = { _id:string; name:string; phone:string; email?:string; location:string; approximateArea?:string; existingFlooring?:string; demolition?:string; materialSupply?:string; utmSource?:string; utmMedium?:string; utmCampaign?:string; utmTerm?:string; gclid?:string; status?:string; estimatedValue?:number; finalJobValue?:number; notes?:string; createdAt:string };

export default function LeadDashboard(){
 const [key,setKey]=useState(''); const [leads,setLeads]=useState<Lead[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [statusFilter,setStatusFilter]=useState('All'); const [sourceFilter,setSourceFilter]=useState('All'); const [query,setQuery]=useState('');
 const load=async()=>{setLoading(true);setError('');const r=await fetch('/api/admin/leads',{headers:{'x-admin-key':key}});const d=await r.json();setLoading(false);if(!r.ok)return setError(d.error||'Unable to load leads.');setLeads(d.leads||[])};
 const save=async(lead:Lead,patch:Partial<Lead>)=>{setError('');const r=await fetch('/api/admin/leads',{method:'PATCH',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify({id:lead._id,...patch})});const d=await r.json();if(!r.ok)return setError(d.error||'Unable to save lead.');setLeads(c=>c.map(x=>x._id===lead._id?d.lead:x));if(d.conversionEvent&&window.gtag)window.gtag('event',d.conversionEvent,{lead_id:lead._id,lead_source:lead.utmSource||'direct',campaign:lead.utmCampaign||'',value:d.conversionEvent==='won_job'?(d.lead.finalJobValue||0):undefined,currency:'USD'})};
 const sources=useMemo(()=>Array.from(new Set(leads.map(l=>l.utmSource||'direct'))).sort(),[leads]);
 const shown=useMemo(()=>leads.filter(l=>(statusFilter==='All'||(l.status||'New')===statusFilter)&&(sourceFilter==='All'||(l.utmSource||'direct')===sourceFilter)&&(!query||`${l.name} ${l.location} ${l.phone} ${l.email||''}`.toLowerCase().includes(query.toLowerCase()))),[leads,statusFilter,sourceFilter,query]);
 const m=useMemo(()=>({total:leads.length,qualified:leads.filter(l=>['Qualified','Estimate Scheduled','Estimate Sent','Won'].includes(l.status||'')).length,estimates:leads.filter(l=>['Estimate Scheduled','Estimate Sent','Won'].includes(l.status||'')).length,won:leads.filter(l=>l.status==='Won').length,revenue:leads.reduce((s,l)=>s+(l.finalJobValue||0),0)}),[leads]);
 return <main className="min-h-screen bg-[#0f1111] px-4 py-24 text-white sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#d6ad63]">mOliora</p><h1 className="mt-2 text-3xl font-bold">Flooring Lead Dashboard</h1><p className="mt-2 text-sm text-white/60">Ad click → lead → qualified → estimate → won job.</p>
 <div className="mt-6 flex max-w-xl gap-2"><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Admin CRM key" className="min-w-0 flex-1 rounded-lg border border-white/15 bg-white/5 px-4 py-3"/><button onClick={load} className="rounded-lg bg-[#d6ad63] px-5 py-3 font-bold text-black">{loading?'Loading…':'Open CRM'}</button></div>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}
 {leads.length>0&&<><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-5">{[['Leads',m.total],['Qualified',m.qualified],['Estimates',m.estimates],['Won',m.won],['Won revenue',`$${m.revenue.toLocaleString()}`]].map(([a,b])=><div key={String(a)} className="rounded-xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase text-white/50">{a}</p><p className="mt-1 text-2xl font-bold">{b}</p></div>)}</div>
 <div className="mt-5 grid gap-2 sm:grid-cols-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, city, phone…" className="rounded-lg border border-white/10 bg-white/5 px-3 py-2"/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-lg bg-[#202323] px-3 py-2"><option>All</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)} className="rounded-lg bg-[#202323] px-3 py-2"><option>All</option>{sources.map(s=><option key={s}>{s}</option>)}</select></div>
 <p className="mt-3 text-xs text-white/45">Showing {shown.length} of {leads.length}. Qualified, estimate and won status changes are recorded as GA4 events. GCLID is retained for Google Ads offline conversion import.</p>
 <div className="mt-6 space-y-4">{shown.map(l=><article key={l._id} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{l.name} · {l.location}</h2><p className="text-sm text-white/65"><a href={`tel:${l.phone}`}>{l.phone}</a>{l.email?` · ${l.email}`:''} · {new Date(l.createdAt).toLocaleString()}</p></div><select value={l.status||'New'} onChange={e=>save(l,{status:e.target.value})} className="rounded-lg bg-[#202323] px-3 py-2 text-sm">{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="mt-4 grid gap-2 text-sm text-white/75 sm:grid-cols-3"><p><b>Area:</b> {l.approximateArea||'—'}</p><p><b>Existing:</b> {l.existingFlooring||'—'}</p><p><b>Removal:</b> {l.demolition||'—'}</p><p><b>Material:</b> {l.materialSupply||'—'}</p><p><b>Source:</b> {l.utmSource||'direct'} / {l.utmMedium||'—'}</p><p><b>Campaign:</b> {l.utmCampaign||'—'}</p><p><b>Keyword:</b> {l.utmTerm||'—'}</p><p className="sm:col-span-2"><b>GCLID:</b> {l.gclid||'—'}</p></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs text-white/55">Estimated value<input defaultValue={l.estimatedValue||''} onBlur={e=>save(l,{estimatedValue:Number(e.target.value)||0})} type="number" min="0" className="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2"/></label><label className="text-xs text-white/55">Final job value<input defaultValue={l.finalJobValue||''} onBlur={e=>save(l,{finalJobValue:Number(e.target.value)||0})} type="number" min="0" className="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2"/></label><label className="text-xs text-white/55">Notes<textarea defaultValue={l.notes||''} onBlur={e=>save(l,{notes:e.target.value})} className="mt-1 h-20 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2"/></label></div></article>)}</div></>}
 </div></main>
}
