'use client';

import { useEffect, useMemo, useState, useTransition } from 'react';

type ExistingFloor='none'|'carpet'|'floating'|'hardwood'|'tile'; type Trim='keep'|'reinstall'|'new'|'shoe'; type Material='have'|'value'|'premium'|'heavy'; type Subfloor='good'|'minor'|'unsure';
const field='min-h-12 w-full rounded-xl border border-white/15 bg-black/35 px-4 py-3 text-white outline-none focus:border-[#d6ad63]';
const choice=(on:boolean)=>`rounded-xl border px-4 py-3 text-left transition ${on?'border-[#d6ad63] bg-[#d6ad63]/15 text-white':'border-white/10 bg-white/[.025] text-white/65 hover:border-white/25'}`;
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n); const r100=(n:number)=>Math.round(n/100)*100;
function Icon(){return <svg viewBox="0 0 72 72" className="h-12 w-12" fill="none" aria-hidden><path d="M10 24c0-5 4-9 9-9h29c5 0 9 4 9 9v5H22c-5 0-9 4-9 9s4 9 9 9h35v7c0 5-4 9-9 9H19c-5 0-9-4-9-9V24Z" stroke="currentColor" strokeWidth="2.6"/><path d="M18 15v-2c0-3 2-5 5-5h24c3 0 5 2 5 5v2" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round"/><rect x="39" y="31" width="25" height="31" rx="5" fill="#111313" stroke="currentColor" strokeWidth="2.6"/><rect x="44" y="36" width="15" height="6" rx="2" stroke="currentColor" strokeWidth="2"/><path d="M44.5 48h3m5.5 0h3m-11.5 6h3m5.5 0h3" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round"/><circle cx="24" cy="38" r="2.5" fill="currentColor"/><path d="M61 14v7M57.5 17.5h7" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round"/></svg>}
export default function LvpProjectEstimator(){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[contact,setContact]=useState(false),[sent,setSent]=useState(false),[pending,startTransition]=useTransition(),[error,setError]=useState('');
 const [mode,setMode]=useState<'dimensions'|'sqft'>('dimensions'),[length,setLength]=useState(''),[width,setWidth]=useState(''),[sqft,setSqft]=useState(''),[location,setLocation]=useState('');
 const [floor,setFloor]=useState<ExistingFloor>('carpet'),[remove,setRemove]=useState(true),[trim,setTrim]=useState<Trim>('keep'),[doors,setDoors]=useState(1),[stairs,setStairs]=useState(0),[subfloor,setSubfloor]=useState<Subfloor>('unsure'),[material,setMaterial]=useState<Material>('have');
 useEffect(()=>{
   document.body.style.overflow=open?'hidden':'';
   const hidden=new Map<HTMLElement,string>();
   const hideRoomvo=()=>{
     if(!open)return;
     const selectors='iframe[src*="roomvo.com"], [id*="roomvo" i], [class*="roomvo" i], [id*="ffPopup" i], [class*="ffPopup" i], iframe[name*="ffPopup" i]';
     document.querySelectorAll<HTMLElement>(selectors).forEach(el=>{
       let target=el;
       let parent=el.parentElement;
       while(parent&&parent!==document.body){
         const position=getComputedStyle(parent).position;
         if(position==='fixed'||position==='sticky'){target=parent;break;}
         parent=parent.parentElement;
       }
       if(!hidden.has(target)){
         hidden.set(target,target.style.cssText);
         target.style.setProperty('display','none','important');
         target.style.setProperty('visibility','hidden','important');
         target.style.setProperty('pointer-events','none','important');
       }
     });
   };
   hideRoomvo();
   const observer=open?new MutationObserver(hideRoomvo):null;
   if(observer)observer.observe(document.body,{childList:true,subtree:true});
   return()=>{
     document.body.style.overflow='';
     observer?.disconnect();
     hidden.forEach((style,el)=>{el.style.cssText=style;});
   };
 },[open]);
 const estimate=useMemo(()=>{const l=Number(length),w=Number(width),area=mode==='dimensions'?l*w:Number(sqft);if(!area||area<=0)return null;const perimeter=mode==='dimensions'?2*(l+w):4.5*Math.sqrt(area);let total=area*3.25;if(remove)total+=area*({none:0,carpet:1,floating:1.25,hardwood:2.5,tile:4}[floor]);total+=perimeter*({keep:0,reinstall:2,new:4.75,shoe:2.75}[trim])+doors*65+stairs*150;if(subfloor==='minor')total+=area*.5;if(subfloor==='unsure')total+=area*.25;total+=area*1.1*({have:0,value:2.5,premium:4,heavy:6}[material]);total=Math.max(total,700);return{sqft:Math.round(area),perimeter:Math.round(perimeter),low:r100(total*.92),high:r100(total*(subfloor==='unsure'?1.2:1.15))}},[length,width,sqft,mode,floor,remove,trim,doors,stairs,subfloor,material]);
 const floorName={none:'Bare subfloor',carpet:'Carpet',floating:'LVP / laminate',hardwood:'Hardwood',tile:'Tile'}[floor]; const trimName={keep:'Keep existing trim',reinstall:'Remove & reinstall',new:'New baseboards',shoe:'Shoe / quarter-round'}[trim]; const materialName={have:'Customer has flooring',value:'Value LVP',premium:'Premium LVP',heavy:'Heavy-duty / premium LVP'}[material];
 const canNext=step===0?!!estimate:step===1?!!location.trim():true;
 async function submit(form:HTMLFormElement){if(!estimate)return;const d=new FormData(form),range=`${money(estimate.low)}–${money(estimate.high)}`,dimensions=mode==='dimensions'?`${length} × ${width} ft`:`${estimate.sqft} sq ft`;const message=[`LVP PROJECT CALCULATOR — customer requested exact quote`,`Calculator range shown: ${range}`,`Size: ${dimensions} (${estimate.sqft} sq ft)`,`Trim perimeter: ${estimate.perimeter} linear ft`,`Existing flooring: ${floorName}`,`Removal: ${remove?'Yes':'No'}`,`Trim: ${trimName}`,`Doorways / estimated transitions: ${doors}`,`Stairs: ${stairs}`,`Subfloor: ${subfloor}`,`Material: ${materialName}`].join('\n');const payload={name:String(d.get('name')||''),phone:String(d.get('phone')||''),email:String(d.get('email')||''),location,service:'LVP Flooring',approximateArea:`${estimate.sqft} sq ft`,existingFlooring:floorName,demolition:remove?'Yes':'No',materialSupply:material==='have'?'I already have flooring':`Need Moliora — ${materialName}`,message,consent:d.get('consent')==='true',website:'',leadSource:'LVP Project Calculator',landingPage:window.location.pathname+window.location.search};startTransition(async()=>{try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),json=await res.json();if(!res.ok||!json.success){setError(json.error||'Could not submit request.');return}setSent(true)}catch{setError('Unexpected error. Please try again.')}})}
 const labels=['Space','Location','Floor','Details','Materials','Estimate'];
 return <>
  <button type="button" onClick={()=>{setOpen(true);setStep(0);setContact(false)}} className="group w-full rounded-2xl border border-[#d6ad63]/55 bg-[linear-gradient(135deg,rgba(214,173,99,.20),rgba(255,255,255,.035))] p-5 text-left shadow-[0_16px_40px_rgba(0,0,0,.28)] transition hover:-translate-y-0.5 hover:border-[#f0c978] sm:p-6"><div className="flex items-center gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl border border-[#d6ad63]/50 bg-black/35 text-[#f0c978] shadow-inner"><Icon/></div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#d6ad63]">Plan your project</p><h3 className="mt-1 text-xl font-semibold sm:text-2xl">Plan Your Project & Request a Quote</h3><p className="mt-1 text-sm leading-5 text-white/55">Build the project, see your estimated range, then send the same details to us in one flow.</p></div><span className="ml-auto hidden text-2xl text-[#d6ad63] sm:block">→</span></div></button>
  {open&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/80 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true"><div className="max-h-[94dvh] w-full max-w-3xl overflow-y-auto rounded-t-3xl border border-white/10 bg-[#111313] shadow-2xl sm:rounded-3xl">
   <div className="sticky top-0 z-10 border-b border-white/10 bg-[#111313]/95 px-5 py-4 backdrop-blur sm:px-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.28em] text-[#d6ad63]">LVP Project Planner</p><p className="mt-1 text-sm text-white/55">Step {step+1} of 6 · {labels[step]}</p></div><button onClick={()=>setOpen(false)} className="flex h-10 w-10 items-center justify-center rounded-full border border-white/15 text-xl text-white/70" aria-label="Close">×</button></div><div className="mt-3 grid grid-cols-6 gap-1">{labels.map((x,i)=><div key={x} className={`h-1 rounded-full ${i<=step?'bg-[#d6ad63]':'bg-white/10'}`}/>)}</div></div>
   <div className="p-5 sm:p-8">
    {sent?<div className="py-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-[#d6ad63]/50 text-2xl text-[#f0c978]">✓</div><h3 className="mt-5 text-3xl font-semibold">We have your project.</h3><p className="mt-3 text-white/60">Your selections and the estimate range were saved with your quote request.</p><button onClick={()=>setOpen(false)} className="mt-6 rounded-xl bg-[#d6ad63] px-6 py-3 font-bold text-black">Done</button></div>:<>
     {step===0&&<div><h3 className="text-3xl font-semibold">Tell us about your space</h3><p className="mt-2 text-white/55">Enter dimensions and we’ll calculate the floor area and trim perimeter automatically.</p><div className="mt-6 flex gap-2"><button onClick={()=>setMode('dimensions')} className={choice(mode==='dimensions')}>Room dimensions</button><button onClick={()=>setMode('sqft')} className={choice(mode==='sqft')}>I know sq ft</button></div>{mode==='dimensions'?<div className="mt-4 grid grid-cols-2 gap-3"><input value={length} onChange={e=>setLength(e.target.value)} type="number" className={field} placeholder="Length, ft"/><input value={width} onChange={e=>setWidth(e.target.value)} type="number" className={field} placeholder="Width, ft"/></div>:<input value={sqft} onChange={e=>setSqft(e.target.value)} type="number" className={`${field} mt-4`} placeholder="Square feet"/>}{estimate&&<div className="mt-4 rounded-xl border border-[#d6ad63]/25 bg-[#d6ad63]/[.07] p-4 text-sm"><b>{estimate.sqft} sq ft detected</b>{mode==='dimensions'&&<span className="block mt-1 text-white/55">Approx. {estimate.perimeter} linear ft room perimeter</span>}</div>}</div>}
     {step===1&&<div><h3 className="text-3xl font-semibold">Where is the project?</h3><p className="mt-2 text-white/55">City or ZIP helps us confirm the service area.</p><input value={location} onChange={e=>setLocation(e.target.value)} className={`${field} mt-6`} placeholder="St. Paul, MN or ZIP"/></div>}
     {step===2&&<div><h3 className="text-3xl font-semibold">What is on the floor now?</h3><div className="mt-6 grid gap-2 sm:grid-cols-3">{([['none','Bare subfloor'],['carpet','Carpet'],['floating','LVP / Laminate'],['hardwood','Hardwood'],['tile','Tile']] as const).map(([v,n])=><button key={v} onClick={()=>setFloor(v)} className={choice(floor===v)}>{n}</button>)}</div>{floor!=='none'&&<label className="mt-5 flex gap-3 text-sm text-white/70"><input type="checkbox" checked={remove} onChange={e=>setRemove(e.target.checked)} className="accent-[#d6ad63]"/>Include removal of existing floor</label>}</div>}
     {step===3&&<div><h3 className="text-3xl font-semibold">Room details</h3><p className="mt-2 text-white/55">We use the room perimeter for trim and doorways as estimated transitions.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{([['keep','Keep existing trim'],['reinstall','Remove & reinstall'],['new','Install new baseboards'],['shoe','Add shoe / quarter-round']] as const).map(([v,n])=><button key={v} onClick={()=>setTrim(v)} className={choice(trim===v)}>{n}</button>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-sm">Doorways / transitions<input value={doors} onChange={e=>setDoors(Math.max(0,+e.target.value))} type="number" min="0" className={`${field} mt-2`}/></label><label className="text-sm">LVP-covered stairs<input value={stairs} onChange={e=>setStairs(Math.max(0,+e.target.value))} type="number" min="0" className={`${field} mt-2`}/></label></div><p className="mt-3 text-sm text-[#e9c985]">{doors} estimated transition{doors===1?'':'s'} · {estimate?.perimeter||0} ft trim perimeter</p></div>}
     {step===4&&<div><h3 className="text-3xl font-semibold">Floor condition & material</h3><p className="mt-5 text-sm font-semibold">Subfloor condition</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{([['good','Looks good'],['minor','Minor issues'],['unsure','Not sure']] as const).map(([v,n])=><button key={v} onClick={()=>setSubfloor(v)} className={choice(subfloor===v)}>{n}</button>)}</div><p className="mt-6 text-sm font-semibold">New LVP material</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{([['have','I already have flooring'],['value','Help source — Value'],['premium','Help source — Premium'],['heavy','Help source — Heavy-duty']] as const).map(([v,n])=><button key={v} onClick={()=>setMaterial(v)} className={choice(material===v)}>{n}</button>)}</div></div>}
     {step===5&&estimate&&<div className="text-center"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#d6ad63]">Estimated project range</p><p className="mt-4 text-4xl font-semibold text-[#f0c978] sm:text-5xl">{money(estimate.low)} – {money(estimate.high)}</p><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-white/50">Preliminary planning range based on your selections. Final pricing is confirmed after measurements, product selection and site conditions are reviewed.</p>{!contact?<button onClick={()=>setContact(true)} className="mt-7 rounded-xl bg-[#d6ad63] px-7 py-3.5 text-sm font-bold uppercase tracking-wider text-black">Request My Exact Quote</button>:<form onSubmit={e=>{e.preventDefault();submit(e.currentTarget)}} className="mt-7 text-left"><p className="mb-4 text-center text-sm text-white/55">Your project details are already attached. Just tell us how to reach you.</p><div className="grid gap-3 sm:grid-cols-3"><input name="name" required className={field} placeholder="Name"/><input name="phone" required type="tel" className={field} placeholder="Phone"/><input name="email" required type="email" className={field} placeholder="Email"/></div><label className="mt-4 flex gap-3 text-sm text-white/55"><input name="consent" value="true" required type="checkbox" className="accent-[#d6ad63]"/>I agree that Moliora may contact me about this flooring request.</label>{error&&<p className="mt-3 text-sm text-red-200">{error}</p>}<button disabled={pending} className="mt-5 w-full rounded-xl bg-[#d6ad63] px-6 py-3.5 font-bold text-black disabled:opacity-50">{pending?'Sending…':'Submit Quote Request'}</button></form>}</div>}
     {!contact&&<div className="sticky bottom-0 z-10 -mx-5 mt-8 flex items-center justify-between border-t border-white/10 bg-[#111313]/95 px-5 py-4 pb-[calc(1rem+env(safe-area-inset-bottom))] backdrop-blur sm:-mx-8 sm:px-8"><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="px-4 py-3 text-sm text-white/60 disabled:opacity-20">← Back</button>{step<5&&<button disabled={!canNext} onClick={()=>setStep(s=>Math.min(5,s+1))} className="rounded-xl bg-[#d6ad63] px-7 py-3 text-sm font-bold text-black disabled:opacity-30">Continue →</button>}</div>}
    </>}
   </div>
  </div></div>}
 </>
}
