import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/context/themeContext';
import Menu from '@/components/Menu/Menu';
import { cookies } from 'next/headers';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const themeCookie = cookies().get('theme')?.value as
        | 'light'
        | 'dark'
        | undefined;
    const initialTheme = themeCookie ?? 'light';

    return (
        <html lang="en" className={initialTheme}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} container mx-auto antialiased`}
            >
                <ThemeProvider>
                    <header className="container">
                        <Menu />
                    </header>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
